# Generated by Django 4.1 on 2022-12-11 09:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Login",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[("objects", django.contrib.auth.models.UserManager()),],
        ),
        migrations.CreateModel(
            name="Addmissing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("state", models.CharField(default="kerala", max_length=100)),
                (
                    "District",
                    models.CharField(
                        choices=[
                            ("TRIVANDRUM", "TRIVANDRUM"),
                            ("KOLLAM", "KOLLAM"),
                            ("PATHANAMTHITTA", "PATHANAMTHITTA"),
                            ("IDUKKI", "IDUKKI"),
                            ("ALAPPUZHA", "ALAPPUZHA"),
                            ("PALAKKAD", "PALAKKAD"),
                            ("THRISSUR", "THRISSUR"),
                            ("ERNAKULAM", "ERNAKULAM"),
                            ("MALAPPURAM", "MALAPPURAM"),
                            ("WAYANAD", "WAYANAD"),
                            ("KOTTAYAM", "KOTTAYAM"),
                            ("KOZHIKODE", "KOZHIKODE"),
                            ("KANNUR", "KANNUR"),
                            ("KASARAGOD", "KASARAGODE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("crime_no", models.CharField(max_length=100)),
                ("crime_category", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="image")),
            ],
        ),
        migrations.CreateModel(
            name="Criminalreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("state", models.CharField(default="kerala", max_length=100)),
                (
                    "District",
                    models.CharField(
                        choices=[
                            ("TRIVANDRUM", "TRIVANDRUM"),
                            ("KOLLAM", "KOLLAM"),
                            ("PATHANAMTHITTA", "PATHANAMTHITTA"),
                            ("IDUKKI", "IDUKKI"),
                            ("ALAPPUZHA", "ALAPPUZHA"),
                            ("PALAKKAD", "PALAKKAD"),
                            ("THRISSUR", "THRISSUR"),
                            ("ERNAKULAM", "ERNAKULAM"),
                            ("MALAPPURAM", "MALAPPURAM"),
                            ("WAYANAD", "WAYANAD"),
                            ("KOTTAYAM", "KOTTAYAM"),
                            ("KOZHIKODE", "KOZHIKODE"),
                            ("KANNUR", "KANNUR"),
                            ("KASARAGOD", "KASARAGODE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("crime_no", models.CharField(max_length=100)),
                ("crime_category", models.CharField(max_length=100)),
                ("photo", models.ImageField(upload_to="image/criminal")),
            ],
        ),
        migrations.CreateModel(
            name="Detection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("crime_no", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Notify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=100)),
                ("Notification_message", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Publicreg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "MALE"),
                            ("FEMALE", "FEMALE"),
                            ("OTHERS", "OTHERS"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("address", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=100)),
                ("state", models.CharField(default="kerala", max_length=100)),
                (
                    "District",
                    models.CharField(
                        choices=[
                            ("TRIVANDRUM", "TRIVANDRUM"),
                            ("KOLLAM", "KOLLAM"),
                            ("PATHANAMTHITTA", "PATHANAMTHITTA"),
                            ("IDUKKI", "IDUKKI"),
                            ("ALAPPUZHA", "ALAPPUZHA"),
                            ("PALAKKAD", "PALAKKAD"),
                            ("THRISSUR", "THRISSUR"),
                            ("ERNAKULAM", "ERNAKULAM"),
                            ("MALAPPURAM", "MALAPPURAM"),
                            ("WAYANAD", "WAYANAD"),
                            ("KOTTAYAM", "KOTTAYAM"),
                            ("KOZHIKODE", "KOZHIKODE"),
                            ("KANNUR", "KANNUR"),
                            ("KASARAGOD", "KASARAGODE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("photo", models.ImageField(upload_to="image")),
                ("aadhar", models.FileField(upload_to="image")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="public",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Policereg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("pin_code", models.CharField(max_length=100)),
                ("state", models.CharField(default="Kerala", max_length=100)),
                (
                    "District",
                    models.CharField(
                        choices=[
                            ("TRIVANDRUM", "TRIVANDRUM"),
                            ("KOLLAM", "KOLLAM"),
                            ("PATHANAMTHITTA", "PATHANAMTHITTA"),
                            ("IDUKKI", "IDUKKI"),
                            ("ALAPPUZHA", "ALAPPUZHA"),
                            ("PALAKKAD", "PALAKKAD"),
                            ("THRISSUR", "THRISSUR"),
                            ("ERNAKULAM", "ERNAKULAM"),
                            ("MALAPPURAM", "MALAPPURAM"),
                            ("WAYANAD", "WAYANAD"),
                            ("KOTTAYAM", "KOTTAYAM"),
                            ("KOZHIKODE", "KOZHIKODE"),
                            ("KANNUR", "KANNUR"),
                            ("KASARAGOD", "KASARAGODE"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("phone_number", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("photo", models.ImageField(upload_to="image")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="police",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Complaint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(max_length=100)),
                ("complaint_msg", models.TextField(max_length=100)),
                ("reply", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
